# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install ultralytics

import os
import shutil
import xml.etree.ElementTree as ET
import yaml
from ultralytics import YOLO

base_dir = '/content/parkir'
dest_img_dir = '/content/dataset/train/images'

os.makedirs(dest_img_dir, exist_ok=True)

count = 0
for r, d, files in os.walk(base_dir):
    for f in files:
        if f.lower().endswith(('.png', '.jpg', '.jpeg')):
            shutil.copy(os.path.join(r, f), os.path.join(dest_img_dir, f))
            count += 1

print(f"{count} gambar pindah ke folder training.")

xml_path = [os.path.join(r, f) for r, d, files in os.walk('/content/parkir') for f in files if f.endswith('.xml')][0]
root = ET.parse(xml_path).getroot()
class_mapping = {'free_parking_space': 0, 'not_free_parking_space': 1, 'partially_free_parking_space': 1}

for image in root.findall('image'):
    name = os.path.basename(image.get('name'))

    if os.path.exists(os.path.join('/content/dataset/train/images', name)):
        txt_path = os.path.join('/content/dataset/train/labels', os.path.splitext(name)[0] + '.txt')
        w, h = float(image.get('width')), float(image.get('height'))

        with open(txt_path, 'w') as f:
            for poly in image.findall('polygon'):
                label = poly.get('label')
                if label in class_mapping:
                    points = [float(p) for pair in poly.get('points').split(';') for p in pair.split(',')]
                    xs, ys = points[0::2], points[1::2]
                    x1, x2, y1, y2 = min(xs), max(xs), min(ys), max(ys)

                    xc, yc = ((x1 + x2) / 2) / w, ((y1 + y2) / 2) / h
                    bw, bh = (x2 - x1) / w, (y2 - y1) / h
                    f.write(f"{class_mapping[label]} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")

print("Berhasil membuat label ")

yaml_data = {
    'path': '/content/dataset',
    'train': 'train/images',
    'val': 'train/images',
    'names': {v: k for k, v in class_mapping.items()}
}
with open('/content/dataset/data.yaml', 'w') as f:
    yaml.dump(yaml_data, f)

print("File data.yaml telah dibuat.")

model = YOLO('yolov8n.pt')
model.train(data='/content/dataset/data.yaml', epochs=50, imgsz=640)

results = model.predict(source='/content/dataset/train/images/', conf=0.25, save=True)

print("Prediksi selesai")

import glob
import os
from IPython.display import Image, display

semua_folder_prediksi = glob.glob('/content/runs/detect/predict*')

if not semua_folder_prediksi:
    print("Belum ada folder")
else:
    folder_terbaru = max(semua_folder_prediksi, key=os.path.getctime)
    print(f"Mencari gambar {folder_terbaru}")

    gambar_hasil = glob.glob(os.path.join(folder_terbaru, '*.*'))
    gambar_hasil = [img for img in gambar_hasil if img.endswith(('.png', '.jpg', '.jpeg'))]

    if not gambar_hasil:
        print("gambar kosong")
    else:
        for image_path in gambar_hasil[:3]:
            print(f"🖼️ Menampilkan: {os.path.basename(image_path)}")
            display(Image(filename=image_path))